### ISSUE TITLE
[Bug] Heroku website is down

### ISSUE THREAD

**Issue by lporras** [bundler/bundler-slackin#1]
I want to participate in the Google Summer of Code version 2023, and when reading this wiki page: [Getting-Involved](https://github.com/rubygsoc/rubygsoc/wiki/Getting-Involved), I found that this [Heroku link](https://bundler-slackin.herokuapp.com/) is broken, it adds you to the slack channel.

<img width="586" alt="Captura de pantalla 2023-03-22 a la(s) 10 23 43 a m" src="https://user-images.githubusercontent.com/232293/226953401-5d25aa53-a6db-4093-9433-cf6b8a118f93.png">

Is there any other way to get invited to this slack?

**Comment by simi** [comment]
Hello, I have invited you manually for now using email in your GitHub public profile. We're going to revive this site soon.

**Comment by simi** [comment]
Should be addressed by https://github.com/rubygems/bundler-site/pull/1120 for now :pray: .

**Comment by lporras** [comment]
@simi I just saw that the fix was merged and the web page is now working, I'm closing this issue.
